version: "3.8"

services:
  execution:
    image: ethpandaops/geth:master-5b57727
    command:
      - --networkid=28256
      - --state.scheme=path
      - --verbosity=3
      - --datadir=/execution-data
      - --http
      - --http.addr=0.0.0.0
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=admin,engine,net,eth,web3,debug
      - --http.port=8545
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,engine,net,eth,web3,debug
      - --ws.origins=*
      - --allow-insecure-unlock
      - --nat=extip:${IP_ADDRESS}
      - --verbosity=3
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      - --syncmode=full
      - --rpc.allow-unprotected-txs
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=9001
      - --port=50403
      - --discovery.port=50403
      - --bootnodes=enode://30674d1f5fa3cf763c2d991eeaf585db42c45737a4d47aee3653b50ac33947437769e13f04c12bab63d5c2a416d08b2637e6340d13b7d59489f0ac8dae919756@88.99.94.109:50303?discport=50303
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "10645:8545" 
      - "10646:8546" 
      - "10651:8551" 
      - "11101:9001" 
      - "50403:50403/udp"
      - "50403:50403/tcp"
    restart: unless-stopped

  beacon:
    image: sigp/lighthouse:v4.5.0
    user: "root"
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --disable-enr-auto-update
      - --enr-address=${IP_ADDRESS}
      - --enr-udp-port=11100
      - --enr-tcp-port=11100
      - --listen-address=0.0.0.0
      - --port=11100
      - --http
      - --http-address=0.0.0.0
      - --http-port=4000
      - --http-allow-sync-stalled
      - --slots-per-restore-point=32
      - --disable-packet-filter
      - --execution-endpoints=http://execution:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --subscribe-all-subnets
      - --import-all-attestations
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5054
      - --trusted-peers=16Uiu2HAm4GXc2aYZkdfHvvn56s6zEdoSAwdiNcGkzvXX5y4MX4U4
      - --boot-nodes=/ip4/88.99.94.109/udp/11000/udp/16Uiu2HAm4GXc2aYZkdfHvvn56s6zEdoSAwdiNcGkzvXX5y4MX4U4
      - --libp2p-addresses=/ip4/88.99.94.109/tcp/11000/p2p/16Uiu2HAm4GXc2aYZkdfHvvn56s6zEdoSAwdiNcGkzvXX5y4MX4U4
      - --enable-private-discovery=true
      - --target-peers=16
      - --disable-optimistic-finalized-sync
      - --disable-backfill-rate-limiting
      - --genesis-backfill
      - --reconstruct-historic-states
      - --reset-payload-statuses
      - --disable-peer-scoring
    volumes:
      - ./consensus-data:/consensus-data 
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "11100:11100/udp"
      - "11100:11100/tcp" 
      - "4300:4000"
      - "7354:5054"
    depends_on:
      - execution
    restart: unless-stopped

  validator:
    image: sigp/lighthouse:v4.5.0
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --validators-dir=/validator-keys/node-1-keystores/keys
      - --secrets-dir=/validator-keys/node-1-keystores/secrets
      - --init-slashing-protection
      - --http
      - --unencrypted-http-transport
      - --http-address=0.0.0.0
      - --http-port=5042
      - --beacon-nodes=http://beacon:4000
      - --suggested-fee-recipient=0x8943545177806ED17B9F23F0a21ee5948eCaa776
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-allow-origin=*
      - --metrics-port=5064
    volumes:
      - ./el-cl-genesis-data:/el-cl-genesis-data
      - ./validator-keys:/validator-keys
    ports:
      - "7142:5042"
      - "7164:5064"
    depends_on:
      - beacon
    restart: unless-stopped
